# Generated by Django 5.2.12 on 2026-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('current_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('IN_DEFECT', 'In Defect'), ('IN_REPAIR', 'In Repair'), ('WAITING_RETEST', 'Waiting Retest'), ('REPAIRED', 'Repaired')], db_index=True, default='HEALTHY', max_length=30)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boards_board',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['serial_number'], name='boards_boar_serial__7225fa_idx'), models.Index(fields=['reference'], name='boards_boar_referen_897347_idx'), models.Index(fields=['current_status'], name='boards_boar_current_5fc5a3_idx'), models.Index(fields=['last_seen_at'], name='boards_boar_last_se_144ff7_idx')],
            },
        ),
    ]
