# Generated by Django 5.2.12 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='board',
            name='boards_boar_referen_897347_idx',
        ),
        migrations.RemoveField(
            model_name='board',
            name='reference',
        ),
        migrations.AddField(
            model_name='board',
            name='client_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='board',
            name='internal_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['client_reference'], name='boards_boar_client__12e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['internal_reference'], name='boards_boar_interna_3e4021_idx'),
        ),
    ]
