# Generated by Django 5.2.12 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('entity_type', models.CharField(db_index=True, default='TESTER', max_length=50)),
                ('entity_key', models.CharField(db_index=True, max_length=150)),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alerts_alert_event',
                'ordering': ['-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('alert_type', models.CharField(choices=[('REPEATED_DEFECT_MESSAGE', 'Repeated Defect Message'), ('HIGH_FAILURE_RATE', 'High Failure Rate'), ('LOW_FPY', 'Low FPY')], db_index=True, max_length=30)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('time_window_minutes', models.PositiveIntegerField(default=60)),
                ('consecutive_count', models.PositiveIntegerField(default=3)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alerts_alert_rule',
                'ordering': ['name'],
            },
        ),
    ]
