# Generated by Django 5.2.12 on 2026-04-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('designation', models.CharField(db_index=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=150)),
                ('affectation_type', models.CharField(choices=[('TESTER', 'Tester'), ('BAY', 'Bay'), ('INSTRUMENT', 'Instrument'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('affectation_value', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('METER', 'Mètre'), ('LITER', 'Litre')], default='PIECE', max_length=20)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pdr_part',
                'ordering': ['part_code'],
            },
        ),
        migrations.CreateModel(
            name='PartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pdr.part')),
            ],
            options={
                'db_table': 'pdr_part_stock',
                'ordering': ['part__part_code'],
            },
        ),
        migrations.CreateModel(
            name='PartStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement')], db_index=True, max_length=20)),
                ('source_type', models.CharField(choices=[('CURATIVE', 'Curative'), ('PREVENTIVE', 'Preventive'), ('MANUAL', 'Manual'), ('INVENTORY', 'Inventory')], db_index=True, default='MANUAL', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('source_reference', models.CharField(blank=True, default='', max_length=150)),
                ('performed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pdr.part')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdr_stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdr_part_stock_movement',
                'ordering': ['-performed_at', '-id'],
            },
        ),
    ]
