# Generated by Django 5.2.12 on 2026-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_remove_board_boards_boar_referen_897347_idx_and_more'),
        ('failures', '0002_remove_failurecase_failures_fa_referen_f5a74d_idx_and_more'),
        ('testresults', '0002_remove_testresult_testresults_referen_713a15_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(db_index=True, max_length=100)),
                ('target_entity_type', models.CharField(db_index=True, max_length=50)),
                ('target_entity_key', models.CharField(db_index=True, max_length=150)),
                ('score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('predicted_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intelligence_prediction',
                'ordering': ['-predicted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_outcome', models.CharField(db_index=True, default='UNKNOWN', max_length=50)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('client_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('internal_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('detected_in_phase', models.CharField(db_index=True, max_length=30)),
                ('detected_on_tester', models.CharField(db_index=True, max_length=100)),
                ('failure_type', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('technician_matricule', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('detected_cause', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('action_result', models.CharField(blank=True, default='', max_length=50)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('repair_started_at', models.DateTimeField(blank=True, null=True)),
                ('repair_completed_at', models.DateTimeField(blank=True, null=True)),
                ('retest_result', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_histories', to='boards.board')),
                ('failure_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_histories', to='failures.failurecase')),
                ('source_test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_histories', to='testresults.testresult')),
            ],
            options={
                'db_table': 'intelligence_repair_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
