# Generated by Django 5.2.12 on 2026-04-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('testresults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('failure_status', models.CharField(choices=[('IN_DEFECT', 'In Defect'), ('IN_REPAIR', 'In Repair'), ('WAITING_RETEST', 'Waiting Retest'), ('REPAIRED', 'Repaired')], db_index=True, default='IN_DEFECT', max_length=30)),
                ('detected_in_phase', models.CharField(choices=[('BOARD_TEST', 'Board Test'), ('DIELECTRIC_TEST', 'Dielectric Test'), ('BURN_IN_TEST', 'Burn In Test'), ('FINAL_TEST', 'Final Test')], db_index=True, max_length=30)),
                ('detected_on_tester', models.CharField(db_index=True, max_length=100)),
                ('failure_type', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_cases', to='boards.board')),
                ('source_test_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_cases', to='testresults.testresult')),
            ],
            options={
                'db_table': 'failures_failure_case',
                'ordering': ['-opened_at', '-id'],
                'indexes': [models.Index(fields=['serial_number'], name='failures_fa_serial__44a8c7_idx'), models.Index(fields=['reference'], name='failures_fa_referen_f5a74d_idx'), models.Index(fields=['failure_status'], name='failures_fa_failure_520dfe_idx'), models.Index(fields=['detected_in_phase'], name='failures_fa_detecte_a875b1_idx'), models.Index(fields=['detected_on_tester'], name='failures_fa_detecte_fd41e2_idx'), models.Index(fields=['opened_at'], name='failures_fa_opened__3213ba_idx')],
            },
        ),
    ]
