# Generated by Django 5.2.12 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_board_boards_boar_referen_897347_idx_and_more'),
        ('failures', '0001_initial'),
        ('testresults', '0002_remove_testresult_testresults_referen_713a15_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='failurecase',
            name='failures_fa_referen_f5a74d_idx',
        ),
        migrations.RemoveField(
            model_name='failurecase',
            name='reference',
        ),
        migrations.AddField(
            model_name='failurecase',
            name='client_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='failurecase',
            name='internal_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='failurecase',
            name='detected_in_phase',
            field=models.CharField(choices=[('BOARD_TEST', 'Test carte'), ('NORMATIVE_TEST', 'Test normatif'), ('BURN_IN_TEST', 'Test déverminage'), ('LEAK_TEST', 'Test étanchéité'), ('FINAL_TEST', 'Test final')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='failurecase',
            index=models.Index(fields=['client_reference'], name='failures_fa_client__6ccd09_idx'),
        ),
        migrations.AddIndex(
            model_name='failurecase',
            index=models.Index(fields=['internal_reference'], name='failures_fa_interna_fffdb1_idx'),
        ),
    ]
