# Generated by Django 5.2.12 on 2026-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('calibration_frequency_months', models.PositiveIntegerField(default=12)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('OUT_OF_SERVICE', 'Out of Service')], db_index=True, default='VALID', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='maintenance.maintenanceasset')),
            ],
            options={
                'db_table': 'calibration_instrument',
                'ordering': ['instrument_code'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, default='', max_length=150)),
                ('calibration_date', models.DateField(db_index=True)),
                ('next_due_date', models.DateField(db_index=True)),
                ('result', models.CharField(choices=[('CONFORM', 'Conform'), ('NON_CONFORM', 'Non Conform')], db_index=True, max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='calibration_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='calibration.instrument')),
            ],
            options={
                'db_table': 'calibration_record',
                'ordering': ['-calibration_date', '-id'],
            },
        ),
    ]
