# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationrecord",
            name="calibration_state",
            field=models.CharField(
                choices=[
                    ("GOOD", "Bon"),
                    ("RESTRICTED", "Utilisation avec restrictions"),
                    ("KO", "KO"),
                ],
                db_index=True,
                default="GOOD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="affectation",
            field=models.CharField(blank=True, db_index=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="instrument",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="instrument",
            name="calibration_state",
            field=models.CharField(
                choices=[
                    ("GOOD", "Bon"),
                    ("RESTRICTED", "Utilisation avec restrictions"),
                    ("KO", "KO"),
                ],
                db_index=True,
                default="GOOD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="conformity_status",
            field=models.CharField(
                choices=[("CONFORM", "Conforme"), ("NON_CONFORM", "Non conforme")],
                db_index=True,
                default="CONFORM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="sub_family_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="instrument",
            name="type_code",
            field=models.CharField(
                choices=[
                    ("CHARGE", "Charge"),
                    ("DIELECTRIC", "Dielectric"),
                    ("GB_TESTER", "GB TESTER"),
                    ("MESURE", "Mesure"),
                    ("MULTIMETRE", "Multimetre"),
                    ("OSCILL", "Oscill"),
                    ("SWITCH", "Switch"),
                ],
                db_index=True,
                default="MESURE",
                max_length=30,
            ),
        ),
    ]
