# Generated by Django 5.2.12 on 2026-04-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('pdr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('TESTER', 'Tester'), ('BAY', 'Bay'), ('BENCH', 'Bench'), ('INSTRUMENT', 'Instrument')], db_index=True, max_length=20)),
                ('tester_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_BREAKDOWN', 'In Breakdown'), ('IN_MAINTENANCE', 'In Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], db_index=True, default='ACTIVE', max_length=20)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=150)),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('serial_number', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_asset',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='CurativeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('trigger_type', models.CharField(choices=[('REPEATED_DEFECT_MESSAGE', 'Repeated Defect Message'), ('HIGH_FAILURE_RATE', 'High Failure Rate'), ('LOW_FPY', 'Low FPY')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('symptom', models.TextField(blank=True, default='')),
                ('failure_cause', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('downtime_start', models.DateTimeField(db_index=True)),
                ('downtime_end', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_VALIDATION', 'Waiting Validation'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('opened_by_system', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_curative_tickets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_curative_tickets', to=settings.AUTH_USER_MODEL)),
                ('source_alert_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curative_tickets', to='alerts.alertevent')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curative_tickets', to='maintenance.maintenanceasset')),
            ],
            options={
                'db_table': 'maintenance_curative_ticket',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CurativePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curative_usages', to='pdr.part')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.curativeticket')),
            ],
            options={
                'db_table': 'maintenance_curative_part',
                'ordering': ['ticket_id', 'part__part_code'],
            },
        ),
        migrations.CreateModel(
            name='CurativeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('failure_cause', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField()),
                ('comment', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curative_actions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='maintenance.curativeticket')),
            ],
            options={
                'db_table': 'maintenance_curative_action',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
