# Generated by Django 5.2.12 on 2026-04-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('pdr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventivePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('<django.db.models.fields.related.ForeignKey>', 'Asset')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_preventive_plan',
                'ordering': ['plan_code'],
            },
        ),
        migrations.CreateModel(
            name='PreventivePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventive_plans', to='pdr.part')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.preventiveplan')),
            ],
            options={
                'db_table': 'maintenance_preventive_part',
                'ordering': ['plan', 'part__part_code'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preventive_schedules', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.preventiveplan')),
            ],
            options={
                'db_table': 'maintenance_preventive_schedule',
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveExecutionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventive_execution_parts', to='pdr.part')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_parts', to='maintenance.preventiveschedule')),
            ],
            options={
                'db_table': 'maintenance_preventive_execution_part',
                'ordering': ['schedule', 'part__part_code'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('task_label', models.CharField(max_length=255)),
                ('instruction', models.TextField(blank=True, default='')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.preventiveplan')),
            ],
            options={
                'db_table': 'maintenance_preventive_task',
                'ordering': ['plan', 'step_order'],
                'unique_together': {('plan', 'step_order')},
            },
        ),
    ]
