# Generated by Django 5.2.12 on 2026-04-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_preventiveplan_preventivepart_preventiveschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiveplan',
            name='asset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preventive_plans', to='maintenance.maintenanceasset'),
        ),
        migrations.AlterField(
            model_name='preventiveplan',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], db_index=True, max_length=50),
        ),
    ]
