# Generated by Django 5.2.12 on 2026-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(db_index=True, max_length=150, unique=True)),
                ('last_source_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('last_source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='IDLE', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'syncengine_sync_cursor',
                'ordering': ['source_table'],
            },
        ),
    ]
