# Generated by Django 5.2.12 on 2026-04-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('test_phase', models.CharField(choices=[('BOARD_TEST', 'Board Test'), ('DIELECTRIC_TEST', 'Dielectric Test'), ('BURN_IN_TEST', 'Burn In Test'), ('FINAL_TEST', 'Final Test')], db_index=True, max_length=30)),
                ('tester_id', models.CharField(db_index=True, max_length=100)),
                ('result', models.CharField(choices=[('FAILED', 'Failed'), ('PASSED', 'Passed'), ('ERROR', 'Error'), ('TERMINATED', 'Terminated')], db_index=True, max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('operator_id', models.CharField(blank=True, default='', max_length=100)),
                ('tested_at', models.DateTimeField(db_index=True)),
                ('source_event_id', models.BigIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='boards.board')),
            ],
            options={
                'db_table': 'testresults_test_result',
                'ordering': ['-tested_at', '-id'],
                'indexes': [models.Index(fields=['serial_number'], name='testresults_serial__35a218_idx'), models.Index(fields=['reference'], name='testresults_referen_713a15_idx'), models.Index(fields=['test_phase'], name='testresults_test_ph_5cdf2a_idx'), models.Index(fields=['tester_id'], name='testresults_tester__a2eef7_idx'), models.Index(fields=['result'], name='testresults_result_f7a693_idx'), models.Index(fields=['tested_at'], name='testresults_tested__1a7690_idx')],
            },
        ),
    ]
