# Generated by Django 5.2.12 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_board_boards_boar_referen_897347_idx_and_more'),
        ('testresults', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testresult',
            name='testresults_referen_713a15_idx',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='comment',
            new_name='failure_message',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='source_event_id',
        ),
        migrations.AddField(
            model_name='testresult',
            name='client_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='failure_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='testresult',
            name='internal_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='testresult',
            name='raw_ingested_ts',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='source_event_key',
            field=models.CharField(db_index=True, default='temp-source-key', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_phase',
            field=models.CharField(choices=[('BOARD_TEST', 'Test carte'), ('NORMATIVE_TEST', 'Test normatif'), ('BURN_IN_TEST', 'Test déverminage'), ('LEAK_TEST', 'Test étanchéité'), ('FINAL_TEST', 'Test final')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['client_reference'], name='testresults_client__e4b621_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['internal_reference'], name='testresults_interna_21e3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['raw_ingested_ts'], name='testresults_raw_ing_a38243_idx'),
        ),
    ]
